site_name: kyro
repo_url: https://github.com/externref/kyro
site_url: https://kyro.externref.dev

theme:
  name: shadcn
  icon: assets/icon.svg
  favicon: assets/icon.svg
  show_title: true 
  show_stargazers: true
  pygments_style:
        light: shadcn-light
        dark: github-dark
  topbar_sections: false 
  katex_options: 
    macros: 
      "\\RR": "\\mathbb{R}" 
      "\\dx": "\\mathrm{d}x"

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.blocks.tab
  - pymdownx.blocks.details

nav:
  - Home: index.md
  - Installation: installation.md
  - Syntax: syntax.md
  - Documentation:
    - core.md
    - std: 
      - std/index.md
      - std/fs.md
      - std/io.md
      - std/os.md
      - std/time.md
      - std/util.md
    - lib:
      - lib/index.md
      - lib/json.md 
      - lib/math.md


